package utramig;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 277892
 */
public class CADASTRO_DE_PRESENÇA extends javax.swing.JFrame {

    /**
     * Creates new form CADASTRO_DE_PRESENÇA
     */
    public CADASTRO_DE_PRESENÇA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMatricula = new javax.swing.JLabel();
        jLabelFaltas = new javax.swing.JLabel();
        jLabelAulas = new javax.swing.JLabel();
        jTextFieldmatricula = new javax.swing.JTextField();
        jTextFieldfaltas = new javax.swing.JTextField();
        jTextFieldaulas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonfrequencia = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelpreencha = new javax.swing.JLabel();
        jLabelaprovado = new javax.swing.JLabel();
        jLabelreprovado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMatricula.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelMatricula.setText("Matrícula:");

        jLabelFaltas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelFaltas.setText("Total de Faltas:");

        jLabelAulas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelAulas.setText("Total de Aulas:");

        jTextFieldmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmatriculaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Controle de Presença");

        jButtonfrequencia.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButtonfrequencia.setText("Frequência");
        jButtonfrequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfrequenciaActionPerformed(evt);
            }
        });

        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelFaltas)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldfaltas))
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelAulas)
                                .addComponent(jLabelMatricula))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelreprovado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonfrequencia, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addComponent(jTextFieldaulas)
                                .addComponent(jTextFieldmatricula)
                                .addComponent(jLabelaprovado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabelpreencha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFaltas)
                    .addComponent(jTextFieldfaltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAulas)
                    .addComponent(jTextFieldaulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelpreencha, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jButtonfrequencia)
                .addGap(18, 18, 18)
                .addComponent(jLabelaprovado, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelreprovado, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmatriculaActionPerformed

    private void jButtonfrequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfrequenciaActionPerformed
        String matricula;
        double faltas, aulas;
        matricula = jTextFieldmatricula.getText();
        faltas = Double.valueOf(jTextFieldfaltas.getText());
        aulas = Double.valueOf(jTextFieldaulas.getText());
               
       
      if (aulas>0 || faltas >0){
          
          if (faltas<=((aulas*25)/100)){
              jLabelaprovado.setText("Aprovado");
          }
          else {
              jLabelaprovado.setText("Reprovado");
          }
      }
      if (aulas==0|| faltas ==0){
          
          jLabelpreencha.setText("Erro de nota");
      }
     
       
      if (faltas<=(25*aulas )/100){
        
    }
          
      
      
      
    }//GEN-LAST:event_jButtonfrequenciaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         { dispose();}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CADASTRO_DE_PRESENÇA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CADASTRO_DE_PRESENÇA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CADASTRO_DE_PRESENÇA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CADASTRO_DE_PRESENÇA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CADASTRO_DE_PRESENÇA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonfrequencia;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAulas;
    private javax.swing.JLabel jLabelFaltas;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelaprovado;
    private javax.swing.JLabel jLabelpreencha;
    private javax.swing.JLabel jLabelreprovado;
    private javax.swing.JTextField jTextFieldaulas;
    private javax.swing.JTextField jTextFieldfaltas;
    private javax.swing.JTextField jTextFieldmatricula;
    // End of variables declaration//GEN-END:variables
}
