package utramig;


import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 277892
 */
public class CADASTRO_DE_ALUNO extends javax.swing.JFrame {

    /**
     * Creates new form CADASTRO_DE_ALUNO
     */
    public CADASTRO_DE_ALUNO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupsexo = new javax.swing.ButtonGroup();
        jLabelnome = new javax.swing.JLabel();
        jTextFieldnome = new javax.swing.JTextField();
        jLabelmatricula = new javax.swing.JLabel();
        jTextFieldmatricula = new javax.swing.JTextField();
        jLabelsexo = new javax.swing.JLabel();
        jLabelturma = new javax.swing.JLabel();
        jTextFieldturma = new javax.swing.JTextField();
        jLabelcadastrodealuno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablecadastrar = new javax.swing.JTable();
        jButtoncadastrar = new javax.swing.JButton();
        jLabeltelefone = new javax.swing.JLabel();
        jFormattedTextFieldtelefone = new javax.swing.JFormattedTextField();
        jLabelbairro = new javax.swing.JLabel();
        jLabelcidade = new javax.swing.JLabel();
        jTextFieldbairro = new javax.swing.JTextField();
        jTextFieldcidade = new javax.swing.JTextField();
        jLabelendereco = new javax.swing.JLabel();
        jTextFieldendereco = new javax.swing.JTextField();
        jRadioButtonFem = new javax.swing.JRadioButton();
        jRadioButtonMas = new javax.swing.JRadioButton();
        jLabelpreencha = new javax.swing.JLabel();
        jLabelpreencha1 = new javax.swing.JLabel();
        jButtonsair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelnome.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelnome.setText("Nome:");

        jTextFieldnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnomeActionPerformed(evt);
            }
        });

        jLabelmatricula.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelmatricula.setText("Matrícula:");

        jLabelsexo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelsexo.setText("Sexo:");

        jLabelturma.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelturma.setText("Turma:");

        jLabelcadastrodealuno.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelcadastrodealuno.setText("CADASTRO DO ALUNO");

        jTablecadastrar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTablecadastrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "CIDADE", "ENDEREÇO", "BAIRRO", "SEXO", "TURMA", "MATRÍCULA", "TELEFONE"
            }
        ));
        jScrollPane1.setViewportView(jTablecadastrar);

        jButtoncadastrar.setText("CADASTRAR");
        jButtoncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncadastrarActionPerformed(evt);
            }
        });

        jLabeltelefone.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabeltelefone.setText("Telefone:");

        try {
            jFormattedTextFieldtelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldtelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldtelefoneActionPerformed(evt);
            }
        });

        jLabelbairro.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelbairro.setText("Bairro:");

        jLabelcidade.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelcidade.setText("Cidade:");

        jLabelendereco.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelendereco.setText("Endereço:");

        buttonGroupsexo.add(jRadioButtonFem);
        jRadioButtonFem.setText("Feminino");
        jRadioButtonFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemActionPerformed(evt);
            }
        });

        buttonGroupsexo.add(jRadioButtonMas);
        jRadioButtonMas.setText("Masculino");

        jButtonsair.setText("SAIR");
        jButtonsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelnome)
                    .addComponent(jLabelcidade)
                    .addComponent(jLabelbairro)
                    .addComponent(jLabelendereco))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelcadastrodealuno)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldcidade, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldnome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldbairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelpreencha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelturma)
                                        .addComponent(jLabelsexo))
                                    .addGap(59, 59, 59)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonFem)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonMas))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jFormattedTextFieldtelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                            .addComponent(jTextFieldmatricula)
                                            .addComponent(jTextFieldturma)))
                                    .addContainerGap(67, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelmatricula)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelpreencha1)
                                    .addContainerGap(249, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabeltelefone)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtoncadastrar)
                        .addGap(264, 264, 264))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonsair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelcadastrodealuno)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonFem)
                            .addComponent(jRadioButtonMas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelnome)
                            .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelsexo))
                        .addGap(3, 3, 3)))
                .addComponent(jLabelpreencha)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldcidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelcidade, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelturma)
                            .addComponent(jTextFieldturma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelmatricula)
                            .addComponent(jTextFieldmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelendereco))
                        .addGap(20, 20, 20)))
                .addComponent(jLabelpreencha1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelbairro)
                    .addComponent(jTextFieldbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltelefone)
                    .addComponent(jFormattedTextFieldtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButtoncadastrar)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonsair)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnomeActionPerformed

    private void jButtoncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncadastrarActionPerformed
    { String nome, cidade, matricula,endereco, bairro, sexo = null, turma,  telefone ;
      nome = jTextFieldnome.getText(); 
      matricula = jTextFieldmatricula.getText();
      turma = jTextFieldturma.getText();
      cidade = jTextFieldcidade.getText();
      bairro = jTextFieldbairro.getText();
      telefone = jFormattedTextFieldtelefone.getText();
      endereco = jTextFieldendereco.getText();

          
      if ((nome== null || nome.equals("")) || (matricula==null || matricula.equals("")))
      {  jLabelpreencha.setText("Preencha os campo");  }
      else{ jLabelpreencha.setText(" ");   }
      
      
      if (jRadioButtonFem.isSelected()) 
      {    sexo = "Feminino";  }
      else if  (jRadioButtonMas.isSelected())
      { sexo = "Masculino";   }

      DefaultTableModel Modelcadastrar= (DefaultTableModel)jTablecadastrar.getModel();
      Object []informacoes = {nome, cidade, endereco, bairro,sexo, turma, matricula,  telefone };
      Modelcadastrar.addRow (informacoes);
      
    
     
    }
    }//GEN-LAST:event_jButtoncadastrarActionPerformed

    private void jRadioButtonFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFemActionPerformed

    private void jButtonsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsairActionPerformed
        { dispose();}
    }//GEN-LAST:event_jButtonsairActionPerformed

    private void jFormattedTextFieldtelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldtelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldtelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CADASTRO_DE_ALUNO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CADASTRO_DE_ALUNO().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupsexo;
    private javax.swing.JButton jButtoncadastrar;
    private javax.swing.JButton jButtonsair;
    private javax.swing.JFormattedTextField jFormattedTextFieldtelefone;
    private javax.swing.JLabel jLabelbairro;
    private javax.swing.JLabel jLabelcadastrodealuno;
    private javax.swing.JLabel jLabelcidade;
    private javax.swing.JLabel jLabelendereco;
    private javax.swing.JLabel jLabelmatricula;
    private javax.swing.JLabel jLabelnome;
    private javax.swing.JLabel jLabelpreencha;
    private javax.swing.JLabel jLabelpreencha1;
    private javax.swing.JLabel jLabelsexo;
    private javax.swing.JLabel jLabeltelefone;
    private javax.swing.JLabel jLabelturma;
    private javax.swing.JRadioButton jRadioButtonFem;
    private javax.swing.JRadioButton jRadioButtonMas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablecadastrar;
    private javax.swing.JTextField jTextFieldbairro;
    private javax.swing.JTextField jTextFieldcidade;
    private javax.swing.JTextField jTextFieldendereco;
    private javax.swing.JTextField jTextFieldmatricula;
    private javax.swing.JTextField jTextFieldnome;
    private javax.swing.JTextField jTextFieldturma;
    // End of variables declaration//GEN-END:variables
}
