package utramig;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 277892
 */
public class CONTROLE_DE_NOTAS extends javax.swing.JFrame {

    /**
     * Creates new form CONTROLE_DE_NOTAS
     */
    public CONTROLE_DE_NOTAS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelmatricula = new javax.swing.JLabel();
        jLabelBim1 = new javax.swing.JLabel();
        jLabelBim2 = new javax.swing.JLabel();
        jTextFieldmatricula = new javax.swing.JTextField();
        jTextFieldBim1 = new javax.swing.JTextField();
        jTextFieldBim2 = new javax.swing.JTextField();
        jLabeltotal = new javax.swing.JLabel();
        jTextFieldtotal = new javax.swing.JTextField();
        jButtonresultado = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelAprovado = new javax.swing.JLabel();
        jLabelReprovado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Controle de Notas");

        jLabelmatricula.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelmatricula.setText("Matrícula:");

        jLabelBim1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelBim1.setText("1° Bimestre:");

        jLabelBim2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelBim2.setText("2° Bimestre:");

        jTextFieldBim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBim1ActionPerformed(evt);
            }
        });

        jLabeltotal.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabeltotal.setText("Total:");

        jButtonresultado.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButtonresultado.setText("Resultado");
        jButtonresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresultadoActionPerformed(evt);
            }
        });

        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelmatricula)
                    .addComponent(jLabelBim1)
                    .addComponent(jLabelBim2)
                    .addComponent(jLabeltotal))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldtotal)
                    .addComponent(jTextFieldBim2)
                    .addComponent(jTextFieldmatricula)
                    .addComponent(jTextFieldBim1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonresultado)
                        .addGap(40, 40, 40))
                    .addComponent(jLabelAprovado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelReprovado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelmatricula)
                    .addComponent(jTextFieldmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBim1)
                    .addComponent(jTextFieldBim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBim2)
                    .addComponent(jTextFieldBim2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButtonresultado)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltotal))
                .addGap(28, 28, 28)
                .addComponent(jLabelAprovado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabelReprovado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBim1ActionPerformed

    private void jButtonresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresultadoActionPerformed
        String matricula; double Bim1, Bim2, total;
        matricula = jTextFieldmatricula.getText();
        Bim1 = Double.valueOf(jTextFieldBim1.getText());
        Bim2 = Double.valueOf(jTextFieldBim2.getText());
        total = Bim1+Bim2;
        
        
        if (Bim1>=60)
        { jLabelAprovado.setText("Aprovado");   }
        else { jLabelReprovado.setText("Reprovado");  }
    
        if (Bim2>=60)
        { jLabelAprovado.setText("Aprovado");   }
        else { jLabelReprovado.setText("Reprovado");  }
     
            
            
            
            
            
            
            
       
   
    }//GEN-LAST:event_jButtonresultadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         { dispose();}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CONTROLE_DE_NOTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CONTROLE_DE_NOTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CONTROLE_DE_NOTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CONTROLE_DE_NOTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CONTROLE_DE_NOTAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonresultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAprovado;
    private javax.swing.JLabel jLabelBim1;
    private javax.swing.JLabel jLabelBim2;
    private javax.swing.JLabel jLabelReprovado;
    private javax.swing.JLabel jLabelmatricula;
    private javax.swing.JLabel jLabeltotal;
    private javax.swing.JTextField jTextFieldBim1;
    private javax.swing.JTextField jTextFieldBim2;
    private javax.swing.JTextField jTextFieldmatricula;
    private javax.swing.JTextField jTextFieldtotal;
    // End of variables declaration//GEN-END:variables
}
